core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from . import settings
#from . import views



urlpatterns = [
    path('', include('users.urls')),
    path('', include('notes.urls')),
    path('', include('students.urls')),
    #path('', include('notes.urls')),
    path('admin/', admin.site.urls),
    #, # urls de login, register, etc..
]

if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    #urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

notes/urls.py
from django.urls import path, include
from notes import views

urlpatterns = [
    path('new/', views.newNote, name="create"),
    path('notes/', views.getNotes, name="readAll"),
    path('note/<int:id>', views.getNote, name="readOne"),
    path('edit/<int:id>', views.editNote, name="update"),
    path('del/<int:id>', views.delNote, name="delete"),
    #, # urls de login, register, etc..
]

notes/models.py
from django.db import models
from datetime import datetime
from users.models import User
from students.models import Student

# Create your models here.
class Note(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='Auteur')
    student = models.ManyToManyField(Student, related_name='apprenants', verbose_name='Apprenants', blank=True)
    date = models.DateTimeField(default=datetime.today, verbose_name='Date')
    subject = models.CharField(max_length=50, verbose_name='Sujet')
    note = models.TextField(max_length=3000, verbose_name='Note')
    # def __str__(self):
    #     return self.subject

notes/forms.py
from django.forms import ModelForm, TextInput, Textarea, SelectMultiple, DateInput, ModelMultipleChoiceField, ModelChoiceField, Select
from datetime import date
from .models import Note
from students.models import Student
    
class formulaireNote(ModelForm):
    class Meta:
        model = Note
        fields = ('student', 'date', 'subject', 'note',)
        student = ModelMultipleChoiceField(queryset=Student.objects.all(), to_field_name="student")
        widgets = {
            'student': SelectMultiple(attrs={'class': 'form-control', 'size': 1}),
            'date': DateInput(attrs={'type': 'date', 'class': 'date-input', 'value': date.today().strftime("%d-%m-%Y")}),
            'subject': TextInput(attrs={'class': 'form-control'}),
            'note': Textarea(attrs={'class': 'form-control'}),
        }

notes/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from notes.models import Note
from students.models import Student
from .forms import formulaireNote


# Note views
def getNotes(request):
    if request.user.is_authenticated:
        students = Student.objects.all()
        
        try:
            request.session['chosen_student']
        except:
            request.session['chosen_student'] = 0
            
        if int(request.session['chosen_student']) > 0:
            student = Student.objects.all().get(id=request.session['chosen_student'])
            notes = Note.objects.all().filter(student=student).order_by('-id')
        else:
            notes = Note.objects.all().order_by('-id')
            
        if request.method == 'POST':
            request.session['chosen_student'] = int(request.POST['chosen_student'])
            return redirect('/')
                
        chosen = request.session['chosen_student']
        
        return render(request, "notes.html", {"list": notes, "students" : students, 'chosen': chosen})
    else:
        return redirect('/')

def newNote(request):
    
    if request.user.is_authenticated:
        form = formulaireNote()
        #notes = Note.objects.all()
        if request.method == 'POST':
            form = formulaireNote(request.POST)
            if form.is_valid():
                form.save(commit=False)
                def_note = Note.objects.create(
                    author=request.user,
                    date=request.POST['date'],
                    note=request.POST['note'],
                    subject=request.POST['subject'],
                )
                def_note.student.set(request.POST.getlist('student'))
                return render(request, "new.html", {"form": form, "msg": "Note enregistrée avec succès!"})
            
        return render(request, "new.html", {"form": form})
    
    else:
        return redirect('/')

def getNote(request, id):
    
    if request.user.is_authenticated:
        note = Note.objects.all().get(id=id)
        return render(request, "note.html", {"note": note})
    
    else:
        return redirect('/')
    
def editNote(request, id):
    note = Note.objects.all().get(id=id)
    if request.user.is_authenticated and note.author.id == request.user.id:
        students = Student.objects.all()
        chosen = []
        for student in note.student.all():
            chosen.append(student.id)
            
        form = formulaireNote(instance=note)
        if request.method == 'POST':
            form = formulaireNote(request.POST, instance=note)
            if form.is_valid:
                form.save(commit=False)
                def_note = Note.objects.get(id=id)
                def_note.author=request.user
                def_note.date=request.POST['date']
                def_note.note=request.POST['note']
                def_note.subject=request.POST['subject']
                def_note.student.set(request.POST.getlist('student'))
                def_note.save()
                messages.success(request, 'Note modifiée avec succès!')
                return redirect('/note/'+ str(id))
        return render(request, "edit.html", {"note": note, "students": students, "chosen": chosen})
    else:
        return redirect('/')
    
def delNote(request, id):
    note = Note.objects.all().get(id=id)
    if request.user.is_authenticated and note.author.id == request.user.id:
        note.delete()
        messages.success(request, 'Note suprimée avec succès!')
        return redirect('/notes')
    
    else:
        return redirect('/')
    

templates/base.html
{% load bootstrap5 %}
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="icon" href="{% static 'img/favicon.ico' %}" />
  <link rel="stylesheet" href="{% static 'css/styles.css' %}" type="text/css">
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Nunito+Sans&display=swap">
  <script src="https://kit.fontawesome.com/a266ecec7b.js" crossorigin="anonymous"></script>
  {# Load CSS and JavaScript #}
  {% bootstrap_css %}
  {% bootstrap_javascript %}
  <title>Simplon - {% block title %}
    {% endblock %}</title>
</head>

<body>
  {% if user.is_authenticated %}
  <nav class="navbar navbar-expand-lg navbar-dark fw-bold bg-red-simplon py-0">
    <div class="container-fluid">
      <img src="{% static 'img/logo.svg' %}" class="navbar-brand logo">
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText"
        aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarText">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'readAll' %}">Journal</a>
          </li>
          <li class="nav-item">
            <a class="nav-link active" href="{% url 'create' %}">Rédiger</a>
          </li>
        </ul>
        <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <div class="nav-link active">
              {{ user.email }}
            </div>
          </li>
          <li class="nav-item">
            <a class="nav-link active" href="/logout">Déconnexion</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>
  {% endif %}

  <div class="container">
    <div class="row py-5">
      <div class="col">

        {% block content %}
        {% endblock %}
        
      </div>
    </div>
  </div>

</body>

</html>

templates/edit.html
{% extends "base.html" %}

{% block title %}
Modification d'une note
{% endblock %}

{% block content %}
<form method="POST" action="">
    <div class="card border-0 mx-auto" style="max-width: 50rem; width: 100%;">
        <div class="card-body">
            {% csrf_token %}
            <div class="form d-flex flex-column-reverse flex-sm-row justify-content-between">

                <h5 class="card-title fw-bold m-1">Modifier une note</h5>
                <p>
                    <button type="submit" class="btn btn-primary fw-bold">Enregistrer</i></button>
                </p>
            </div>
            <p class="card-text">
            <p class="text-muted fw-bold m-0"><i class="fas fa-graduation-cap me-1 d-inline"></i>
                <select name="student" size=1 class="form-control d-inline" required="" id="id_student"
                    style="width: auto;" multiple>
                    <option value="" disabled>-- Veuillez choisir un apprenant --</option>
                    {% for student in students %}
                    {% if student.id in chosen %}
                    <option value="{{ student.id }}" selected>
                        {% else %}
                    <option value="{{ student.id }}">
                        {% endif %}
                        {{ student.lastname }}
                        {{ student.firstname }}
                    </option>
                    {% endfor %}
                </select>


            </p>
            </p>
            <p class="card-text text-dark fw-bold"><i class="fas fa-info-circle me-1 d-inline"></i>
                <input type="text" name="subject" class="form-control d-inline" maxlength="50" required=""
                    id="id_subject" style="width: auto;" value="{{note.subject}}">
            </p>
            <p class="card-text text-dark">
                <textarea name="note" cols="40" rows="10" class="form-control" maxlength="3000" required=""
                    id="id_note">{{ note.note }}</textarea>
            </p>
            <hr />
            <div class="form d-flex flex-column-reverse flex-sm-row justify-content-between mb-0">
                <p class="text-muted fw-bold mb-0"><i class="fas fa-user me-1"></i>{{note.author}}</p>
                <p class="text-muted fw-bold mb-0">
                    <i class="far fa-calendar-alt me-1 d-inline"></i><input type="date" name="date"
                        value="{{ note.date|date:'Y-m-d' }}" class="date-input d-inline" required="" id="id_date">
                </p>
            </div>
        </div>
    </div>
</form>
{% endblock %}

templates/new.html
{% extends "base.html" %}

{% block title %}
Rédaction
{% endblock %}

{% block content %}
<div class="card border-0 mx-auto" style="max-width: 50rem; width: 100%;">
    <div class="card-body">
        <h5 class="card-title fw-bold m-1">Rédiger une note</h5>
        <p class="card-text">
            {% if msg %}
            <div class="alert alert-success" role="alert">
                <i class="fas fa-info-circle me-1"></i>{{msg}}
              </div>
            {% endif %}
            <form method="post" class="form">
                {% csrf_token %}
                {{form.as_p}}
                <p>
                    <button type="submit" class="btn btn-primary fw-bold">Enregistrer</button>
                </p>
            </form>
        </p>
    </div>
</div>
{% endblock %}

templates/note.html
{% extends "base.html" %}

{% block title %}
Note
{% endblock %}

{% block content %}
<div class="card border-0 mx-auto" style="max-width: 50rem; width: 100%;">
    <div class="card-body">
        <div class="form d-flex flex-column-reverse flex-sm-row justify-content-between">
            <h5 class="card-title fw-bold m-1">Note</h5>
            {% if note.author.id == user.id %}
            <p>
                <a href="{% url 'delete' note.id %}" class="btn btn-danger fw-bold"><i class="fas fa-trash-alt"></i></a>
                <a href="{% url 'update' note.id %}" class="btn btn-primary fw-bold"><i
                        class="fas fa-pencil-alt"></i></a>
            </p>
            {% endif %}
        </div>

        {% if messages %}
        <div class="alert alert-success alert-dismissible fade show" role="alert">
            {% for message in messages %}
            <i class="fas fa-info-circle me-1"></i>{{message}}
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Fermer"></button>
            {% endfor %}
        </div>
        {% endif %}

        <p class="card-text">
        <p class="text-muted fw-bold m-0"><i class="fas fa-graduation-cap me-1"></i>
            {% for student in note.student.all %}
            {{student}}, 
            {% endfor %}
        </p>
        </p>
        <p class="card-text text-dark fw-bold"><i class="fas fa-info-circle me-1"></i>{{note.subject}}
        </p>
        <p class="card-text text-dark">{{ note.note }}</p>
        <hr />
        <div class="form d-flex flex-column-reverse flex-sm-row justify-content-between mb-0">
            <p class="text-muted fw-bold mb-0"><i class="fas fa-user me-1"></i>{{note.author}}</p>
            <p class="text-muted fw-bold mb-0"><i class="far fa-calendar-alt me-1"></i>{{note.date|date:"d/m/Y" }}</p>
        </div>
    </div>
</div>
{% endblock %}

templates/notes.html
{% extends "base.html" %}

{% block title %}
Journal
{% endblock %}

{% block content %}
<div class="card border-0 mx-auto" style="max-width: 50rem; width: 100%;">
    <div class="card-body">
        <form method="post" class="form d-flex flex-column-reverse flex-sm-row justify-content-between">
            <h5 class="card-title fw-bold m-1">Journal de bord</h5>
            {% csrf_token %}
            <p>
                <select name="chosen_student" id="chosen_student" class="form-control d-inline">
                    <option value="0">Voir toutes les notes</option>
                    <option value="" disabled>-- Veuillez choisir un apprenant --</option>
                    {% for student in students %}
                    {% if student.id == chosen %}
                    <option value="{{ student.id }}" selected>
                        {% else %}
                    <option value="{{ student.id }}">
                        {% endif %}
                        {{ student.lastname }}
                        {{ student.firstname }}
                    </option>
                    {% endfor %}
                </select>
                <button type="submit" class="btn btn-primary fw-bold">Trier</button>
            </p>
        </form>
        <p class="card-text">

        {% if messages %}
        <div class="alert alert-success alert-dismissible fade show" role="alert">
            {% for message in messages %}
            <i class="fas fa-info-circle me-1"></i>{{message}}
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Fermer"></button>
            {% endfor %}
        </div>
        {% endif %}


        <div class="row row-cols-1 row-cols-md-2 row-cols-lg-3 g-4">

            {% for note in list %}
            <a href="{% url 'readOne' note.id %}">
                <div class="col">
                    <div class="card border border-2">

                        <div class="card-body">
                            <h5 class="card-title text-dark fw-bold"><i
                                    class="far fa-calendar-alt me-1"></i>{{note.date|date:"d/m/Y" }}</h5>
                            <p class="text-muted fw-bold"><i class="fas fa-user me-1"></i>{{note.author}}</p>
                            <hr />
                            <p class="card-text text-dark fw-bold"><i
                                    class="fas fa-info-circle me-1"></i>{{note.subject}}
                            </p>
                            <p class="card-text text-dark">{{ note.note }}</p>
                            <p class="text-muted fw-bold m-0"><i
                                    class="fas fa-graduation-cap me-1"></i>
                                    {% for student in note.student.all %}
                                        {{student}}<br>
                                    {% endfor %}
                                </p>
                        </div>
                    </div>
                </div>
            </a>
            {% endfor %}

        </div>

        </p>
    </div>
</div>
{% endblock %}